#!/bin/bash
set -e

if [ ! -f "./task.yaml" ]; then
    
    if [ -d "../resources" ] && [ -f "../task.yaml" ]; then
        echo "Changing directory to task root..."
        cd .. # Move from 'tests' subdirectory to task root
    else
        echo "Error: Cannot find task root. Please run this script from the 'harden-docker-security' task directory or its 'tests' subdirectory."
        exit 1
    fi
fi

echo "Current working directory: $(pwd)"

# Define paths relative to the task's root directory
SOLUTION_SCRIPT="./solution.sh"
VERIFY_SCRIPT="./verify.sh"
INSECURE_DOCKERFILE_SRC="./resources/Dockerfile.insecure" # Source for solution
HARDENED_DOCKERFILE_EXPECTED_OUTPUT="./Dockerfile.hardened" # Expected output of solution

# Ensure scripts are executable
chmod +x "$SOLUTION_SCRIPT"
chmod +x "$VERIFY_SCRIPT"

# Clean up any previous run artifacts
rm -f "$HARDENED_DOCKERFILE_EXPECTED_OUTPUT"
# Clean up docker artifacts from previous runs if any (use with caution, specific names)
docker rm -f hardened-app-container-test >/dev/null 2>&1 || true
docker rmi hardened-app-test:latest >/dev/null 2>&1 || true

echo "Running solution script: $SOLUTION_SCRIPT"
# The solution script should take Dockerfile.insecure from ./resources and produce ./Dockerfile.hardened
if ! "$SOLUTION_SCRIPT"; then
    echo "❌ TEST FAIL: Solution script '$SOLUTION_SCRIPT' failed to execute."
    exit 1
fi
echo "✅ Solution script executed successfully."

echo "Checking if hardened Dockerfile was created..."
if [ ! -f "$HARDENED_DOCKERFILE_EXPECTED_OUTPUT" ]; then
    echo "❌ TEST FAIL: Hardened Dockerfile '$HARDENED_DOCKERFILE_EXPECTED_OUTPUT' was not created by the solution script."
    exit 1
fi
echo "✅ Hardened Dockerfile '$HARDENED_DOCKERFILE_EXPECTED_OUTPUT' found."

echo "Running verification script: $VERIFY_SCRIPT"
# The verify script should log its output, which we can capture
# The verify script itself will exit with 0 on success, 1 on failure based on its checks.
# Capture verify.sh output to a log file to avoid polluting test stdout too much
# and to allow verify.sh to use `grep "FAIL:" verify.log` for its own final status
if ! "$VERIFY_SCRIPT" > verify.log 2>&1; then
    echo "❌ TEST FAIL: Verification script '$VERIFY_SCRIPT' indicated failure."
    cat verify.log
    # Attempt to clean up the verify.log generated by verify.sh itself if it fails this way
    # The verify.sh is designed to check its own log, so this is more about the test_docker_security.sh context
    if grep -q "🔴 Overall Status: FAILED" verify.log; then
      echo "Verify script internal checks failed as expected for a failing test."
    fi
    # rm -f verify.log # Clean up log on test script failure
    exit 1
fi

echo "✅ Verification script executed successfully and indicated success."
cat verify.log # Show verification log for review

# Check if verify.log (from verify.sh) contains any "FAIL" messages as a final check from test script perspective
# This is a bit redundant if verify.sh exits with 1 on failure, but good for belt-and-suspenders
if grep -q "❌ FAIL:" verify.log; then
    echo "❌ TEST FAIL: Verification log contains 'FAIL' messages, indicating issues not caught by verify.sh exit code or solution is incomplete."
    # rm -f verify.log # Clean up log
    exit 1
fi

echo "All checks passed for harden-docker-security task."
echo "✅ TEST PASSED"

# Clean up log
rm -f verify.log

exit 0
