#!/bin/bash
set -e # Exit on any error

echo "INFO: Starting verification process for Terraform drift remediation."

# Navigate to the Terraform configuration directory
if [ -d "./resources" ]; then
  CD_TO_RESOURCES=true
  cd ./resources
elif [ ! -f "./main.tf" ]; then
  echo "ERROR: main.tf not found. This script must be run from the root of the 'diagnose_and_fix_terraform_drift' task directory or its 'resources' subdirectory."
  exit 1
fi

echo "Current working directory: $(pwd)"

# Initialize Terraform (should be harmless if already initialized)
echo "INFO: Initializing Terraform..."
terraform init -input=false -no-color > /dev/null

# Check 1: `terraform plan` shows no changes
echo "INFO: Verifying 'terraform plan' shows no changes..."
PLAN_OUTPUT_FILE="verify_plan_output.txt"
# The script should run `terraform plan` and expect no changes (exit code 0).
# Exit code 2 means there are changes, which is a failure for verification.
if terraform plan -input=false -detailed-exitcode -no-color > "$PLAN_OUTPUT_FILE"; then
    echo "✅ PASS: 'terraform plan' shows no pending changes."
    rm "$PLAN_OUTPUT_FILE" # Clean up
else
    PLAN_EXIT_CODE=$?
    if [ $PLAN_EXIT_CODE -eq 2 ]; then
        echo "❌ FAIL: 'terraform plan' indicates there are still pending changes."
        cat "$PLAN_OUTPUT_FILE"
    else
        echo "❌ FAIL: 'terraform plan' failed with exit code $PLAN_EXIT_CODE."
        cat "$PLAN_OUTPUT_FILE"
    fi
    rm "$PLAN_OUTPUT_FILE" # Clean up
    if [ "$CD_TO_RESOURCES" = true ]; then cd ..; fi
    exit 1
fi

# Check 2: Retrieve current resource state using AWS CLI and compare with desired state from Terraform outputs/config
echo "INFO: Verifying actual AWS resource configurations..."

# Load expected values from terraform outputs (should have been generated by solution or setup)
if [ ! -f "terraform_outputs.json" ]; then
    echo "WARN: terraform_outputs.json not found. Attempting to generate."
    terraform output -json > terraform_outputs.json
    if [ ! -f "terraform_outputs.json" ]; then
        echo "❌ FAIL: Could not generate terraform_outputs.json. Cannot verify specific resource attributes."
        if [ "$CD_TO_RESOURCES" = true ]; then cd ..; fi
        exit 1
    fi
fi

BUCKET_NAME=$(jq -r '.s3_bucket_name.value' terraform_outputs.json)
ROLE_NAME=$(jq -r '.iam_role_name.value' terraform_outputs.json)
INSTANCE_PROFILE_NAME=$(jq -r '.iam_instance_profile_name.value' terraform_outputs.json)
AWS_REGION=$(jq -r '.aws_region.value // "us-east-1"' terraform_outputs.json)

# Expected tags from var.common_tags in variables.tf
# Environment = "Test", Project = "TerraformDrift", ManagedBy = "Terraform"
EXPECTED_TAG_ENV_KEY="Environment"
EXPECTED_TAG_ENV_VALUE="Test"
EXPECTED_TAG_PROJ_KEY="Project"
EXPECTED_TAG_PROJ_VALUE="TerraformDrift"
EXPECTED_TAG_MB_KEY="ManagedBy"
EXPECTED_TAG_MB_VALUE="Terraform"

# Verify S3 Bucket Tags
echo "INFO: Verifying tags for S3 bucket '$BUCKET_NAME'..."
S3_TAGS_JSON=$(aws s3api get-bucket-tagging --region $AWS_REGION --bucket $BUCKET_NAME --output json 2>/dev/null || echo "{}")
S3_TAG_ENV_VALUE=$(echo $S3_TAGS_JSON | jq -r --arg KEY "$EXPECTED_TAG_ENV_KEY" '.TagSet[] | select(.Key == $KEY) | .Value')
S3_TAG_PROJ_VALUE=$(echo $S3_TAGS_JSON | jq -r --arg KEY "$EXPECTED_TAG_PROJ_KEY" '.TagSet[] | select(.Key == $KEY) | .Value')
S3_TAG_MB_VALUE=$(echo $S3_TAGS_JSON | jq -r --arg KEY "$EXPECTED_TAG_MB_KEY" '.TagSet[] | select(.Key == $KEY) | .Value')
S3_DRIFT_TAG_EXISTS=$(echo $S3_TAGS_JSON | jq -e '.TagSet[] | select(.Key == "DriftTag")')


if [ "$S3_TAG_ENV_VALUE" == "$EXPECTED_TAG_ENV_VALUE" ] && \
   [ "$S3_TAG_PROJ_VALUE" == "$EXPECTED_TAG_PROJ_VALUE" ] && \
   [ "$S3_TAG_MB_VALUE" == "$EXPECTED_TAG_MB_VALUE" ] && \
   [ "$S3_DRIFT_TAG_EXISTS" == "null" ]; then # jq -e returns exit code 0 if found, 1 if not. Here we want it to be null/not found.
    echo "✅ PASS: S3 bucket '$BUCKET_NAME' tags are correct."
else
    echo "❌ FAIL: S3 bucket '$BUCKET_NAME' tags are incorrect or unexpected 'DriftTag' still exists."
    echo "Expected Environment: $EXPECTED_TAG_ENV_VALUE, Got: $S3_TAG_ENV_VALUE"
    echo "Expected Project: $EXPECTED_TAG_PROJ_VALUE, Got: $S3_TAG_PROJ_VALUE"
    echo "Expected ManagedBy: $EXPECTED_TAG_MB_VALUE, Got: $S3_TAG_MB_VALUE"
    echo "DriftTag exists status: $S3_DRIFT_TAG_EXISTS (should be null or empty)"
    aws s3api get-bucket-tagging --region $AWS_REGION --bucket $BUCKET_NAME --output json
    # exit 1 # Don't exit early, collect all failures
fi

# Verify IAM Role Tags and Policies
echo "INFO: Verifying tags and policies for IAM role '$ROLE_NAME'..."
IAM_ROLE_TAGS_JSON=$(aws iam list-role-tags --region $AWS_REGION --role-name $ROLE_NAME --output json 2>/dev/null || echo "{}")
IAM_TAG_ENV_VALUE=$(echo $IAM_ROLE_TAGS_JSON | jq -r --arg KEY "$EXPECTED_TAG_ENV_KEY" '.Tags[] | select(.Key == $KEY) | .Value')
IAM_TAG_PROJ_VALUE=$(echo $IAM_ROLE_TAGS_JSON | jq -r --arg KEY "$EXPECTED_TAG_PROJ_KEY" '.Tags[] | select(.Key == $KEY) | .Value')
IAM_TAG_MB_VALUE=$(echo $IAM_ROLE_TAGS_JSON | jq -r --arg KEY "$EXPECTED_TAG_MB_KEY" '.Tags[] | select(.Key == $KEY) | .Value')

# Check if the manually added "DriftDemoPolicy" still exists
IAM_DRIFT_POLICY_EXISTS=$(aws iam list-role-policies --region $AWS_REGION --role-name $ROLE_NAME --output json | jq -e '.PolicyNames[] | select(. == "DriftDemoPolicy")')


if [ "$IAM_TAG_ENV_VALUE" == "$EXPECTED_TAG_ENV_VALUE" ] && \
   [ "$IAM_TAG_PROJ_VALUE" == "$EXPECTED_TAG_PROJ_VALUE" ] && \
   [ "$IAM_TAG_MB_VALUE" == "$EXPECTED_TAG_MB_VALUE" ] && \
   [ "$IAM_DRIFT_POLICY_EXISTS" == "null" ]; then # jq -e returns 0 if found, 1 if not. We want not found.
    echo "✅ PASS: IAM role '$ROLE_NAME' tags are correct and 'DriftDemoPolicy' removed."
else
    echo "❌ FAIL: IAM role '$ROLE_NAME' tags are incorrect or 'DriftDemoPolicy' still exists."
    echo "Expected Environment Tag: $EXPECTED_TAG_ENV_VALUE, Got: $IAM_TAG_ENV_VALUE"
    echo "Expected Project Tag: $EXPECTED_TAG_PROJ_VALUE, Got: $IAM_TAG_PROJ_VALUE"
    echo "Expected ManagedBy Tag: $EXPECTED_TAG_MB_VALUE, Got: $IAM_TAG_MB_VALUE"
    echo "'DriftDemoPolicy' exists status: $IAM_DRIFT_POLICY_EXISTS (should be null or empty)"
    aws iam list-role-tags --region $AWS_REGION --role-name $ROLE_NAME --output json
    aws iam list-role-policies --region $AWS_REGION --role-name $ROLE_NAME --output json
    # exit 1
fi

# Verify IAM Instance Profile association
echo "INFO: Verifying IAM role association for instance profile '$INSTANCE_PROFILE_NAME'..."
IP_ROLE_NAME=$(aws iam get-instance-profile --region $AWS_REGION --instance-profile-name $INSTANCE_PROFILE_NAME --output json | jq -r '.InstanceProfile.Roles[] | select(.RoleName == "'$ROLE_NAME'") | .RoleName')

if [ "$IP_ROLE_NAME" == "$ROLE_NAME" ]; then
    echo "✅ PASS: IAM role '$ROLE_NAME' is correctly associated with instance profile '$INSTANCE_PROFILE_NAME'."
else
    echo "❌ FAIL: IAM role '$ROLE_NAME' is NOT correctly associated with instance profile '$INSTANCE_PROFILE_NAME'."
    echo "Expected role: $ROLE_NAME, Got role(s) on profile: $(aws iam get-instance-profile --region $AWS_REGION --instance-profile-name $INSTANCE_PROFILE_NAME --query 'InstanceProfile.Roles[].RoleName' --output text)"
    # exit 1
fi

# Check if any FAIL messages were printed
# A simple grep for "FAIL:" in this script's output to determine final status.
# For this to work, we need to pipe output of this script to a file and then grep that file.
# Or, use a flag variable.
FINAL_STATUS="PASSED"
# Re-check conditions and set FINAL_STATUS
if ! ( [ "$S3_TAG_ENV_VALUE" == "$EXPECTED_TAG_ENV_VALUE" ] && \
       [ "$S3_TAG_PROJ_VALUE" == "$EXPECTED_TAG_PROJ_VALUE" ] && \
       [ "$S3_TAG_MB_VALUE" == "$EXPECTED_TAG_MB_VALUE" ] && \
       [ "$S3_DRIFT_TAG_EXISTS" == "null" ] ); then
    FINAL_STATUS="FAILED"
fi

if ! ( [ "$IAM_TAG_ENV_VALUE" == "$EXPECTED_TAG_ENV_VALUE" ] && \
       [ "$IAM_TAG_PROJ_VALUE" == "$EXPECTED_TAG_PROJ_VALUE" ] && \
       [ "$IAM_TAG_MB_VALUE" == "$EXPECTED_TAG_MB_VALUE" ] && \
       [ "$IAM_DRIFT_POLICY_EXISTS" == "null" ] ); then
    FINAL_STATUS="FAILED"
fi

if [ "$IP_ROLE_NAME" != "$ROLE_NAME" ]; then
    FINAL_STATUS="FAILED"
fi

# The terraform plan check above already exits if it fails.

echo "------------------------------------------"
if [ "$FINAL_STATUS" == "PASSED" ]; then
    echo "✅ Verification Summary: All checks passed."
    if [ "$CD_TO_RESOURCES" = true ]; then cd ..; fi
    exit 0
else
    echo "❌ Verification Summary: One or more checks failed."
    if [ "$CD_TO_RESOURCES" = true ]; then cd ..; fi
    exit 1
fi
