#!/usr/bin/env bash
set -e

TARGET_INFRA_DIR="./resources/target_account_infra"
CICD_INFRA_DIR="./resources/cicd_account_infra"
SETUP_SCRIPT="./resources/setup_accounts.sh"

# Files that the user is supposed to create (iam_roles.tf and iam_policies.tf)
# This solution assumes these files are correctly placed by the user.
# For a fully self-contained solution run, we might copy them from a hidden solution dir.
EXPECTED_TARGET_TF_FILE="$TARGET_INFRA_DIR/iam_roles.tf"
EXPECTED_CICD_TF_FILE="$CICD_INFRA_DIR/iam_policies.tf"

if [ ! -f "$EXPECTED_TARGET_TF_FILE" ]; then
    echo "❌ ERROR: Terraform file for target account '$EXPECTED_TARGET_TF_FILE' not found."
    echo "Please create it as per the task instructions."
    exit 1
fi
if [ ! -f "$EXPECTED_CICD_TF_FILE" ]; then
    echo "❌ ERROR: Terraform file for CI/CD account '$EXPECTED_CICD_TF_FILE' not found."
    echo "Please create it as per the task instructions."
    exit 1
fi

echo "INFO: Starting solution for configuring and testing cross-account IAM access."

# Step 1: Run the setup script to apply Terraform configurations
echo "---------------------------------------------------------------------"
echo "INFO: STEP 1 - Running setup script to create IAM roles and policies via Terraform..."
echo "---------------------------------------------------------------------"
chmod +x "$SETUP_SCRIPT"
if ! "$SETUP_SCRIPT"; then
    echo "❌ ERROR: Setup script '$SETUP_SCRIPT' failed."
    exit 1
fi
echo "✅ Setup script completed. IAM resources should be created."

# Load the Target Deploy Role ARN generated by the setup script
if [ -f "$TARGET_INFRA_DIR/deploy_role_arn.txt" ]; then
    source "$TARGET_INFRA_DIR/deploy_role_arn.txt"
else
    echo "❌ ERROR: Could not find deploy_role_arn.txt. Setup may have failed."
    exit 1
fi

if [ -z "$TARGET_DEPLOY_ROLE_ARN" ]; then
    echo "❌ ERROR: TARGET_DEPLOY_ROLE_ARN is empty. Setup may have failed to output it."
    exit 1
fi
echo "INFO: Target Deploy Role ARN to be assumed: $TARGET_DEPLOY_ROLE_ARN"


# Step 2: Implement and run the test_assume_role.sh logic
echo "---------------------------------------------------------------------"
echo "INFO: STEP 2 - Testing STS AssumeRole and permissions..."
echo "---------------------------------------------------------------------"

# Simulate AWS CLI being configured for the CI/CD account principal (e.g., cicd_user in account 111111111111)
# In a real environment, this would mean `aws configure` was run for this user,
# or AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN are set for this user.
# For this task, we assume the environment executing `aws sts assume-role` has these CICD principal credentials.
echo "INFO: (Simulating AWS CLI context of CI/CD Principal: arn:aws:iam::111111111111:user/cicd_user)"

SESSION_NAME="CICD-TestSession-$(date +%s)"
ASSUMED_ROLE_JSON="assumed_role_credentials.json"

echo "INFO: Attempting to assume role '$TARGET_DEPLOY_ROLE_ARN' with session name '$SESSION_NAME'..."
# In a sandbox without real AWS, this command will likely fail unless STS is perfectly mocked.
# The `verify.sh` will need to be robust to this.
# We use dummy region and output to suppress some errors if CLI isn't fully configured but STS call is mocked.
aws sts assume-role \
    --role-arn "$TARGET_DEPLOY_ROLE_ARN" \
    --role-session-name "$SESSION_NAME" \
    --duration-seconds 900 \
    --output json \
    --region us-east-1 > "$ASSUMED_ROLE_JSON" || {
        echo "❌ ERROR: aws sts assume-role command failed."
        echo "This could be due to incorrect IAM setup, or AWS CLI not configured for CI/CD principal, or STS not available/mocked."
        # cat "$ASSUMED_ROLE_JSON" # Print error if any
        rm -f "$ASSUMED_ROLE_JSON"
        exit 1
    }

if [ ! -s "$ASSUMED_ROLE_JSON" ]; then # Check if file is empty or not created
    echo "❌ ERROR: Failed to obtain assumed role credentials. $ASSUMED_ROLE_JSON is empty or missing."
    exit 1
fi

echo "INFO: Successfully obtained temporary credentials by assuming role."

# Extract temporary credentials
AWS_ACCESS_KEY_ID_TEMP=$(jq -r '.Credentials.AccessKeyId' "$ASSUMED_ROLE_JSON")
AWS_SECRET_ACCESS_KEY_TEMP=$(jq -r '.Credentials.SecretAccessKey' "$ASSUMED_ROLE_JSON")
AWS_SESSION_TOKEN_TEMP=$(jq -r '.Credentials.SessionToken' "$ASSUMED_ROLE_JSON")

if [ "$AWS_ACCESS_KEY_ID_TEMP" == "null" ] || [ "$AWS_SECRET_ACCESS_KEY_TEMP" == "null" ] || [ "$AWS_SESSION_TOKEN_TEMP" == "null" ]; then
    echo "❌ ERROR: Extracted temporary credentials are not valid."
    cat "$ASSUMED_ROLE_JSON"
    rm -f "$ASSUMED_ROLE_JSON"
    exit 1
fi

# Test 1: List S3 buckets (should succeed)
echo "INFO: Testing 'aws s3 ls' using assumed role credentials (should succeed)..."
(
  export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_TEMP"
  export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY_TEMP"
  export AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN_TEMP"
  # Using a dummy region for the command as s3 ls is global but CLI might require one.
  if aws s3 ls --region us-east-1; then
    echo "✅ SUCCESS: 'aws s3 ls' using assumed role succeeded as expected."
  else
    echo "❌ FAIL: 'aws s3 ls' using assumed role failed unexpectedly."
    rm -f "$ASSUMED_ROLE_JSON"
    exit 1
  fi
)

# Test 2: List IAM users (should fail with explicit Deny or implicit Deny)
echo "INFO: Testing 'aws iam list-users' using assumed role credentials (should be denied)..."
(
  export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID_TEMP"
  export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY_TEMP"
  export AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN_TEMP"
  # Using a dummy region for the command.
  if aws iam list-users --region us-east-1 >/dev/null 2>&1; then
    echo "❌ FAIL: 'aws iam list-users' using assumed role SUCCEEDED unexpectedly."
    rm -f "$ASSUMED_ROLE_JSON"
    exit 1
  else
    # Check for specific error message if possible, e.g., AccessDenied
    # For now, any failure is considered success for this negative test.
    echo "✅ SUCCESS: 'aws iam list-users' using assumed role failed as expected (Access Denied)."
  fi
)

# Cleanup temporary credentials file
rm -f "$ASSUMED_ROLE_JSON"

echo "---------------------------------------------------------------------"
echo "INFO: Cross-account IAM role assumption and permission tests completed."
echo "---------------------------------------------------------------------"
exit 0
