#!/bin/bash
set -e

echo "INFO: Starting solution for canary deployment setup..."

# Define resource paths
NGINX_CONF_PATH="resources/nginx/nginx.conf"
DOCKER_COMPOSE_V1_PATH="resources/docker-compose.v1.yml"
DOCKER_COMPOSE_CANARY_PATH="docker-compose.canary.yml" # Output in task root
SET_TRAFFIC_SCRIPT_PATH="set_traffic_split.sh"       # Output in task root

# Step 1: Create docker-compose.canary.yml
echo "INFO: Creating $DOCKER_COMPOSE_CANARY_PATH..."
cat << EOF > "$DOCKER_COMPOSE_CANARY_PATH"
version: '3.8'

services:
  app_v1:
    build:
      context: ./resources/app_v1
      dockerfile: Dockerfile
    image: go_canary_service:v1
    container_name: app_v1_container
    environment:
      - PORT=8081
    networks:
      - canary_net
    # No ports exposed to host directly, Nginx will handle it

  app_v2:
    build:
      context: ./resources/app_v2
      dockerfile: Dockerfile
    image: go_canary_service:v2
    container_name: app_v2_container
    environment:
      - PORT=8082
    networks:
      - canary_net
    # No ports exposed to host directly

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_canary_proxy
    ports:
      - "80:80" # Nginx listens on port 80 for external traffic
    volumes:
      - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount the modified Nginx config
      # We might need a writable path if set_traffic_split.sh modifies nginx.conf from host
      # For now, assume set_traffic_split.sh replaces the file and then reloads nginx from container.
      # A better approach for dynamic Nginx config: use a volume for conf snippets and include them,
      # or use Nginx Plus API, or OpenResty/Lua.
      # For this task, direct replacement and reload is acceptable.
    depends_on:
      - app_v1
      - app_v2
    networks:
      - canary_net

networks:
  canary_net:
    driver: bridge
EOF
echo "INFO: $DOCKER_COMPOSE_CANARY_PATH created."

# Step 2: Modify nginx.conf for traffic splitting (initial 90/10 split)
# This version of nginx.conf will be the one used by docker-compose.canary.yml
echo "INFO: Modifying $NGINX_CONF_PATH for 90/10 traffic split..."
cat << EOF > "$NGINX_CONF_PATH"
events {
    worker_connections 1024;
}

http {
    # Upstream for the stable version (v1)
    upstream app_v1_backend {
        server app_v1:8081; # Service name from docker-compose
    }

    # Upstream for the canary version (v2)
    upstream app_v2_backend {
        server app_v2:8082; # Service name from docker-compose
    }

    # Client splitting configuration
    # We use a cookie "canary_test" to deterministically route for testing if needed.
    # Or a random string for general splitting. For this task, let's use random.
    # A simple approach is upstream weighting if available/simple.
    # Nginx OSS weighting is per-server in upstream block, not dynamic for split_clients.
    # So, split_clients is more versatile here.

    # We'll use a variable that set_traffic_split.sh can change.
    # For initial setup, let's hardcode 90/10.
    # The set_traffic_split.sh will generate a new file with different percentages.

    map \$rand \$backend_server {
        # This map directive will be dynamically generated by set_traffic_split.sh
        # For now, this is a placeholder for the initial 90/10 split logic
        # This is a simplified way to achieve weighted random.
        # A true weighted random often involves more complex logic or commercial Nginx features.
        # For this exercise, we'll use split_clients if it's simpler to manage dynamically.

        # Let's use split_clients, as it's designed for this.
        # The actual percentages are set here for the initial 90/10 split.
        # set_traffic_split.sh will overwrite this block.
        default app_v1_backend; # Fallback, though with 100% total it shouldn't be hit.
    }

    # This is where set_traffic_script.sh will make changes.
    # START_TRAFFIC_SPLIT_CONFIG
    split_clients "\${remote_addr}\${time_iso8601}" \$target_backend {
        90%     app_v1_backend;
        10%     app_v2_backend;
    }
    # END_TRAFFIC_SPLIT_CONFIG


    server {
        listen 80;
        server_name localhost;

        # For testing direct access to versions
        location /v1/ {
            proxy_pass http://app_v1_backend/;
            proxy_set_header Host \$host;
        }
        location /v1/version {
            proxy_pass http://app_v1_backend/version;
            proxy_set_header Host \$host;
        }
        location /v2/ {
            proxy_pass http://app_v2_backend/;
            proxy_set_header Host \$host;
        }
        location /v2/version {
            proxy_pass http://app_v2_backend/version;
            proxy_set_header Host \$host;
        }

        # Main location for canary traffic
        location / {
            # proxy_pass http://\$backend_server; # If using map
            proxy_pass http://\$target_backend; # If using split_clients

            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;
            # Add a header to see which backend was chosen for debugging
            add_header X-Upstream-Target \$target_backend;
        }

        # Generic version endpoint that respects canary split
        location /version {
            # proxy_pass http://\$backend_server/version; # If using map
            proxy_pass http://\$target_backend/version; # If using split_clients
            proxy_set_header Host \$host;
            add_header X-Upstream-Target \$target_backend;
        }
    }
}
EOF
echo "INFO: $NGINX_CONF_PATH modified for initial 90/10 split."

# Step 3: Create set_traffic_split.sh
echo "INFO: Creating $SET_TRAFFIC_SCRIPT_PATH..."
cat << \EOF_SCRIPT > "$SET_TRAFFIC_SCRIPT_PATH"
#!/bin/bash
set -e

NGINX_CONF_FILE="./resources/nginx/nginx.conf" # Relative to task root
DOCKER_COMPOSE_FILE="./docker-compose.canary.yml" # Relative to task root
NGINX_CONTAINER_NAME="nginx_canary_proxy" # As defined in docker-compose.canary.yml

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <percentage_v1> <percentage_v2>"
    echo "Example: $0 70 30"
    exit 1
fi

PERCENT_V1=$1
PERCENT_V2=$2
TOTAL_PERCENT=$((PERCENT_V1 + PERCENT_V2))

if [ "$TOTAL_PERCENT" -ne 100 ]; then
    echo "Error: Percentages must add up to 100."
    exit 1
fi

echo "Setting traffic split: v1=${PERCENT_V1}%, v2=${PERCENT_V2}%"

# Create the new split_clients block content
SPLIT_BLOCK="split_clients \"\${remote_addr}\${time_iso8601}\" \$target_backend {"
if [ "$PERCENT_V1" -gt 0 ] && [ "$PERCENT_V2" -gt 0 ]; then
    SPLIT_BLOCK="${SPLIT_BLOCK}\n        ${PERCENT_V1}%     app_v1_backend;"
    SPLIT_BLOCK="${SPLIT_BLOCK}\n        ${PERCENT_V2}%     app_v2_backend;"
elif [ "$PERCENT_V1" -eq 0 ]; then # 100% to v2
    SPLIT_BLOCK="${SPLIT_BLOCK}\n        100%    app_v2_backend;"
elif [ "$PERCENT_V2" -eq 0 ]; then # 100% to v1
    SPLIT_BLOCK="${SPLIT_BLOCK}\n        100%    app_v1_backend;"
fi
SPLIT_BLOCK="${SPLIT_BLOCK}\n    }"

# Read nginx.conf, replace the block, and write to a temporary file
# Using awk for robust block replacement
awk -v replacement="$SPLIT_BLOCK" '
    BEGIN {p=1}
    /# START_TRAFFIC_SPLIT_CONFIG/ {print; print replacement; p=0}
    /# END_TRAFFIC_SPLIT_CONFIG/ {p=1; next}
    p {print}
' "$NGINX_CONF_FILE" > "${NGINX_CONF_FILE}.tmp"


# Replace the original nginx.conf
mv "${NGINX_CONF_FILE}.tmp" "$NGINX_CONF_FILE"
echo "Nginx configuration updated in $NGINX_CONF_FILE."

# Reload Nginx configuration in the running container
# First, check if the Nginx container is running
if ! docker ps -f name="^/${NGINX_CONTAINER_NAME}$" --format "{{.Names}}" | grep -q "${NGINX_CONTAINER_NAME}"; then
    echo "Warning: Nginx container '$NGINX_CONTAINER_NAME' is not running. Cannot reload configuration."
    echo "The configuration file '$NGINX_CONF_FILE' has been updated."
    echo "Please start the services using 'docker-compose -f $DOCKER_COMPOSE_FILE up -d' for changes to take effect."
    exit 0 # Exit gracefully as file is updated, but reload couldn't happen.
fi

echo "Reloading Nginx configuration in container '$NGINX_CONTAINER_NAME'..."
# Test Nginx configuration syntax inside the container before reloading
# The nginx.conf path inside container is /etc/nginx/nginx.conf
if docker exec "$NGINX_CONTAINER_NAME" nginx -t; then
    # Reload Nginx
    docker exec "$NGINX_CONTAINER_NAME" nginx -s reload
    echo "Nginx reloaded successfully."
else
    echo "Error: Nginx configuration test failed. Check $NGINX_CONF_FILE for errors."
    echo "Nginx was NOT reloaded."
    exit 1
fi

exit 0
EOF_SCRIPT

# Make the script executable
chmod +x "$SET_TRAFFIC_SCRIPT_PATH"
echo "INFO: $SET_TRAFFIC_SCRIPT_PATH created and made executable."

echo "INFO: Solution script finished."
echo "To run the canary setup: docker-compose -f $DOCKER_COMPOSE_CANARY_PATH up -d --build"
echo "To change traffic: ./$SET_TRAFFIC_SCRIPT_PATH <v1_perc> <v2_perc>"
echo "Example: ./$SET_TRAFFIC_SCRIPT_PATH 50 50"
echo "To stop: docker-compose -f $DOCKER_COMPOSE_CANARY_PATH down"

exit 0
